uptick/react-object-list

src/__snapshots__/NPMList.demo.stories.storyshot
src/data-renderers/Table.js
src/data-renderers/__snapshots__/table.stories.storyshot
src/data-renderers/__tests__/__snapshots__/Table.test.js.snap
src/data-renderers/table.stories.js

- Ensure this works with custom renderers and pure text

Use linebreak between multiple renderers in same cell

---

package.json
src/index.js
webpack.config.js
yarn.lock

- Move dependencies to peer dependencies for library-ing
- Adds entry points for filters, renderers, cells

Use peer dependencies

---

src/__snapshots__/ObjectList.stories.storyshot
src/actions-filters/ActionsFiltersContainer.js
src/actions-filters/ActionsFiltersContainer.stories.js
src/actions-filters/__snapshots__/ActionsFiltersContainer.stories.storyshot

- Prevents duplication of search filter
Adds storyshots to cover all cases

Don't rerender search with other filters, pass on value

---

.travis.script.sh
.travis.yml

Adds `yarn build` as a task to the CI matrix

Test whether the package builds

---

src/ObjectList.demo.stories.js

Demo filter was not checking not_contains.

Fixed demo filter

---

README.md
src/ObjectList.js

Take ErrorMessage, Pagination from props

---

src/main.sass

https://uptickhq.atlassian.net/browse/WOR-308

Fix loading overlay to cover table

---

src/ObjectList.stories.js
src/__snapshots__/ObjectList.stories.storyshot
src/main.sass

- Remove padding on search input
- Add search to filters list in story so it shows up

Remove padding, fix search in story and update storyshots

---

src/ObjectList.stories.js
src/__snapshots__/ObjectList.stories.storyshot
src/actions-filters/ActionsFiltersContainer.js
src/actions-filters/__snapshots__/ActionsFiltersContainer.stories.storyshot

Now: Summary, (De)Select All, Custom Actions, Change Columns

Change order of actions above list

---

package.json
src/data-renderers/__tests__/Table.test.js
src/filters/types/__tests__/Date.test.js
src/utils/__tests__/proptypes.test.js
src/utils/proptypes.js
webpack.config.js
yarn.lock

* Exluding subimports from react-day-picker saves 39k in production build
* Remove not needed airbnb props

Optimise webpack build

---

src/filters/__snapshots__/filters.stories.storyshot
src/filters/types/Date.js
src/filters/types/__tests__/__snapshots__/Date.test.js.snap

When updating a filter from a loaded favourite, the date might be stored in YYYY-MM-DD format

Fix date filter for YYYY-MM-DD

---

src/__snapshots__/ObjectList.demo.stories.storyshot
src/__snapshots__/ObjectList.stories.storyshot
src/actions-filters/Favourites.js
src/actions-filters/FavouritesItem.js
src/actions-filters/FiltersContainer.js
src/actions-filters/OptionalFields.js
src/actions-filters/__snapshots__/ActionsFiltersContainer.stories.storyshot
src/actions-filters/__snapshots__/Favourites.stories.storyshot
src/actions-filters/__snapshots__/FiltersContainer.stories.storyshot
src/actions-filters/__tests__/Favourites.test.js
src/actions-filters/__tests__/OptionalFields.test.js
src/data-renderers/Table.js
src/data-renderers/TableHeader.js
src/data-renderers/__tests__/__snapshots__/Table.test.js.snap
src/data-renderers/__tests__/__snapshots__/TableHeader.test.js.snap
src/data-renderers/utils/__tests__/functions.test.js
src/data-renderers/utils/functions.js
src/filters/RemoteMultiChoiceFilter.js
src/filters/__snapshots__/filters.stories.storyshot
src/filters/types/Boolean.js
src/filters/types/__tests__/Boolean.test.js
src/filters/types/__tests__/__snapshots__/Boolean.test.js.snap
src/main.sass
src/utils/__tests__/proptypes.test.js
src/utils/proptypes.js

* When displaying multiple columns under a single value, only display first header
* Default comparison options for remoteChoiceFilter
* Boolean filter only returns value to onChange instead of an object

Fix dataKey accessor for columns

---

.storybook/Storyshots.test.js
__mocks__/react-select/index.js
__mocks__/react-select/lib/Async.js
__mocks__/react-select/lib/default.js
jest.setup.js
src/__snapshots__/ObjectList.stories.storyshot
src/actions-filters/__snapshots__/ActionsFiltersContainer.stories.storyshot
src/actions-filters/__snapshots__/FiltersContainer.stories.storyshot
src/actions-filters/__tests__/SelectFilters.test.js
src/actions-filters/__tests__/__snapshots__/SelectFilters.test.js.snap
src/filters/MultiChoiceFilter.js
src/filters/RemoteChoiceFilter.js
src/filters/RemoteMultiChoiceFilter.js
src/filters/__snapshots__/filters.stories.storyshot
src/filters/types/Choice.js
src/filters/types/__tests__/Choice.test.js
src/filters/types/__tests__/Date.test.js
src/filters/types/__tests__/Day.test.js
src/filters/types/__tests__/__snapshots__/Choice.test.js.snap
src/filters/utils/__tests__/FilterComparison.test.js
src/utils/Select.js

Update react-select translation, autoload by default and fix snapshot tests

Update select translation and add autoload

---

src/ObjectList.demo.stories.js
src/ObjectList.js
src/__snapshots__/ObjectList.demo.stories.storyshot
src/__snapshots__/ObjectList.stories.storyshot
src/colours.sass
src/dark-table.sass
src/data-renderers/List.js
src/data-renderers/List.stories.js
src/data-renderers/ListCard.js
src/data-renderers/Table.js
src/data-renderers/__snapshots__/List.stories.storyshot
src/data-renderers/__snapshots__/table.stories.storyshot
src/data-renderers/__tests__/List.test.js
src/data-renderers/__tests__/Table.test.js
src/data-renderers/__tests__/__snapshots__/List.test.js.snap
src/data-renderers/__tests__/__snapshots__/Table.test.js.snap
src/main.sass

Allows passing of a function to be called when an item in a table or list is clicked on.
Includes hover styling for clickable items.

Add onclick functionality for items in a dataset

---

src/filters/types/Boolean.js
src/filters/types/__tests__/__snapshots__/Boolean.test.js.snap

Boolean filters were not showing the currently selected value. Someone might want to have a quick look to make sure I've not done something stupid. This was the only way I could get it to work.

Fix a bug in boolean filter

---

src/__snapshots__/ObjectList.stories.storyshot
src/actions-filters/__snapshots__/ActionsFiltersContainer.stories.storyshot
src/actions-filters/__snapshots__/FiltersContainer.stories.storyshot
src/filters/__snapshots__/filters.stories.storyshot
src/filters/types/NumberSlider.js
src/filters/types/__tests__/__snapshots__/NumberSlider.test.js.snap
src/main.sass

Ensure slider and input display on one line

---

src/data-renderers/Table.js
src/data-renderers/__tests__/Table.test.js
src/data-renderers/__tests__/__snapshots__/Table.test.js.snap
src/utils/proptypes.js

get row classes from columns

---

src/data-renderers/Table.js
src/utils/functions.js

Allows specification of a column's item renderer as function, class based component, or rendered element (which will be cloned with value and key)

Allow functional and class based components and rendered elements

---

package.json
src/data-renderers/HeaderField.js
src/data-renderers/__tests__/HeaderField.test.js
src/data-renderers/__tests__/__snapshots__/HeaderField.test.js.snap

Allowing for cleaner console logs / errors.

Header field prop to be not required

---

package.json
src/actions-filters/ActionsFiltersContainer.js
src/index.js

export and accept version where only filters are applied
